version: '3.3'
services:
    backend:
      build: .
      command: npm run start:debug
      ports:
        - 8000:3000
        - 9229:9229
      tty: true
      volumes:
        - .:/app
      depends_on:
        - db

    db:
      image: postgres
      ports:
        - "5432:5432"
      restart: always
      volumes:
      - ./data/db:/var/lib/postgresql/data
      environment: 
        - POSTGRES_PASSWORD=postgres